### ISSUE TITLE
can't make it work

### ISSUE THREAD

**Issue by cedmax** [thesp0nge/wordstress#3]
Hi, I think I followed all the right steps: I installed the plugin, got my key and gem installed wordstress, but  then I get this error:

![screenshot 2015-02-25 11](https://cloud.githubusercontent.com/assets/415593/6369751/0ae65ee0-bce1-11e4-8222-07917d724a2d.png)

Could you help me figure out if I am doing something wrong?

**Comment by thesp0nge** [comment]
That was awkward. Support for -k flag was in repository but not on version 0.30.0 gem
Fixed with 0.40.0. 

Please update your gem and thanks for your patience

**Comment by cedmax** [comment]
no problem and thanks for the fix
