### ISSUE TITLE
Php error

### ISSUE THREAD

**Issue by cedmax** [thesp0nge/wordstress#4]
I had to disable the plugin due to a php error on my website

```Warning: strpos(): Offset not contained in string in /path/to/my/website/wp-content/plugins/wordstress/wordstress.php on line 99```

**Comment by thesp0nge** [comment]
Hi Marco, for plugin related issues you can use page on wordpress website.

https://wordpress.org/support/plugin/wordstress

**Comment by thesp0nge** [comment]
However, it sounds to be a warning not a blocking error

**Comment by cedmax** [comment]
will move it there, but it's weird tho: I have all the other warnings not showing up in my website front end, this is the very first one I see being printed there
